install.packages("RColorBrewer", repos='http://cran.us.r-project.org')
install.packages("Rcpp", repos='http://cran.us.r-project.org')
install.packages("VennDiagram", repos='http://cran.us.r-project.org')
install.packages("colorRamps", repos='http://cran.us.r-project.org')
install.packages("cowplot", repos='http://cran.us.r-project.org')
install.packages("dplyr", repos='http://cran.us.r-project.org')
install.packages("ggplot2", repos='http://cran.us.r-project.org')
install.packages("grid", repos='http://cran.us.r-project.org')
install.packages("heatmap3", repos='http://cran.us.r-project.org')
install.packages("lattice", repos='http://cran.us.r-project.org')
install.packages("plyr", repos='http://cran.us.r-project.org')
install.packages("reshape", repos='http://cran.us.r-project.org')
install.packages("reshape2", repos='http://cran.us.r-project.org')
install.packages("scales", repos='http://cran.us.r-project.org')
source("https://bioconductor.org/biocLite.R")
biocLite("DESeq2")
biocLite("edgeR")
biocLite("preprocessCore")
